name: Check-In Quark

on:
  workflow_dispatch:
  schedule:
  - cron: "15 0 * * *"

jobs:
  check-in-quark:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: pip install requests
    - env:
        COOKIE_QUARK: ${{ secrets.COOKIE_QUARK }}
      run: python checkIn_Quark.py
